config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"

  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get "signup", to: "users#new"
  post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 6, maximum: 100}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name


end

app/models/user.rb
class User < ApplicationRecord

  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                     uniqueness: { case_sensitive: false },
                     length: {maximum: 105},
                     format: { with: VALID_EMAIL_REGEX }


  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end 
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created succesfully."
      redirect_to @article #Sends user to article show page
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated succesfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]
    before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category succesfully saved"
      redirect_to @category
    else
      render "new"
    end
  end

  def show


  end

  def index
      @categories = Category.all
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end 
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in succesfuly"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account succesfuly updated"
      redirect_to @user
    else
      render "edit"
    end
  end
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to Room8,#{@user.username} you have succesfuly signed up"
        redirect_to articles_path
      else
        render 'new'
      end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles deleted"
    redirect_to articles_path
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block shadow")
  end




end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<div class="container rounded" id="task-container-1">
  <%= form_with(model: @article, local: true ) do |f| %>
    <div class="form-group row">
      <h3> <%= f.label :Owner, class: "col-form-label" %>   &nbsp;&nbsp; </h3>

        <div class="dropdown">


            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Roomate
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Group</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>

          </div>

          <div class="dropdown">


              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Enzo
              </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="#">Erik</a>
                  <a class="dropdown-item" href="#">Zach</a>
                  <a class="dropdown-item" href="#">Sohail</a>
                </div>

            </div>



    </div>

    <div class="form-group row">
      <%= f.label :Title, class: "col-2 col-form-label" %><br>
      <div class="col-10">
        <%= f.text_area :title, class: "form-control", placeholder: "Title" %>
      </div>
    </div>

    <div class="form-check text-center">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Recurring?</label>
      <div class="dropdown">


          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Monthly
          </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Weekly</a>

            </div>

        </div>
      </div>

    <div class="form-group row text-center">
      <%= f.label :Descrition, class: "col-2 col-form-label" %><br>

        <%= f.text_area :description, class: "shadow-rounded",placeholder: "First of the month" %>



    </div>

    <div class="form-group row text-center">
      <%= f.label :category, class: "col-2 col-form-label" %><br>
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                {prompt: "Make your selecetion from the list below"},
                                {multiple: true, size: 3}) %>




    </div>


    <p class = "text-center">
      <%= f.submit class: "text-white btn-secondary" %>
    </p>
  <% end %>

</div>

app/views/articles/edit.html.erb
<div class = "container-fluid enzosbg" id="page-content">
  <h1><strong>Edit Task</strong></h1>

  <%= render "form" %>



</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/articles/index.html.erb
<div class = "container-fluid enzosbg" id="page-content">


  <div class="row">
    <div class="col-lg-5 shadow-lg p-3 mb-5 rounded" id="task-container-1">
      <h1>Unfinished Tasks</h1>
        <div class="dropdown">
          <div class="text-right">
            Sort By
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Default
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Roomate</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>
            </div>

          </div>
          <ul class="list-group">
            <% @articles.each do |article| %>

                <li class="list-group-item list-group-item-light">
                    <%= link_to article.title, article_path(article), class: "text-info" %>
                    <% if article.categories.any? %>
                      <div class="mt-1"> <%= render article.categories %> </div>
                    <% end %>
                    <div class="text-right">
                      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                        <%= link_to "Complete", article_path(article) %> -
                      <% end %>
                      <%= article.description %> -
                      <small> <i> Created <%= time_ago_in_words( article.created_at) %> ago by <%= article.user.username %> </i> </small>

                    </div>

                </li>

            <% end %>
          </ul>
          <br>

    </div>
    <div class="col-lg-5"id="task-container-1">
      <h1>Pending Approval</h1>
      <div class="dropdown">
        <div class="text-right">
          Sort By
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Default
          </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Roomate</a>
              <a class="dropdown-item" href="#">Date</a>
              <a class="dropdown-item" href="#">Importance</a>
            </div>
          </div>

        </div>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <td><%= article.description %></td>
              <td><%= link_to "Show", article_path(article) %></td>
              <td><%= link_to "Edit", edit_article_path(article) %></td>
              <td><%= link_to "Delete", article_path(article), method: :DELETE, data: {confirm:"Are you sure?"} %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br>
  <br>


  <div class="text-center">
    <button type="button" class="btn btn-secondary btn-lg bt-outline-light"> <strong> <%= link_to "Create new Article", new_article_path, class: "text-white" %></strong></button>
  </div>



</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/articles/new.html.erb
<div class = "container-fluid enzosbg" id="page-content">

  <h1><strong>Create New Task</strong></h1>

  <%= render "form" %>

  

</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/articles/show.html.erb
<div class="container" id="page-content">
  <div class="row">
    <div class="col-lg-12 rounded" id = "show-page">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <%= @article.title %></h5>
          <% if @article.categories.any? %>
            <div class="mt-2"> <%= render @article.categories %> </div>
          <% end %>
          <h6 class="card-subtitle mb-2 text-muted"><small><i> Created <%= time_ago_in_words( @article.created_at) %> ago by <%= @article.user.username %> </i></small></h6>
          <p class="card-text"><%= @article.description %></p>
          <% if logged_in? && (@article.user == current_user || current_user.admin?)  %>
            <%= link_to "Edit", edit_article_path(@article), class: "card-link" %>
            <%= link_to "Delete", article_path(@article), class: "text-danger", method: :DELETE, data: {confirm:"Are you sure?"} %>
          <% end %>


        </div>
      </div>
    </div>
  </div>



</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/index.html.erb
<div class = "container-fluid enzosbg" id="page-content">


  <div class="row">
    <div class="col-lg-5 shadow-lg p-3 mb-5 rounded" id="task-container-1">
      <h1>Categories</h1>
        <div class="dropdown">
          <div class="text-right">
            Sort By
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Default
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Roomate</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>
            </div>

          </div>
          <ul class="list-group">
            <% @categories.each do |category| %>

                <li class="list-group-item list-group-item-light">
                    <%= link_to category.name, category_path(category), class: "text-info" %>
                    <p class="card-text"> <%= pluralize(category.articles.count, "article") %> </p>

                    <div class="text-right">


                      <small> <i> Created <%= time_ago_in_words( category.created_at) %>  </i> </small>

                    </div>

                </li>

            <% end %>
          </ul>
          <br>

    </div>

  </div>

  <br>
  <br>


</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/categories/new.html.erb
<div class = "container-fluid text-center" id="page-content">

  <h1><strong>Create a new Category</strong></h1>


  <div class="container rounded" id="task-container-1">
    <br>
    <%= render "shared/errors", obj: @category %>
    <%= form_with(model: @category, local: true ) do |f| %>


      <div class="form-group row">
        <%= f.label :"Category name", class: "col-2 col-form-label" %><br>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter a Category" %>
        </div>
      </div>






      <p class = "text-center">
        <%= f.submit  class: "text-black btn btn-secondary btn-large btn-outline-light" %>
      </p>
    <% end %>
  <br>
  </div>




</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/categories/show.html.erb
<div class = "container-fluid text-center" id="page-content">

  <h1><strong> <%= @category.name %></strong></h1>
  <div class="row">
    <div class="col-lg-5 shadow-lg p-3 mb-5 rounded" id="task-container-1">
      <h1>Category Tasks</h1>
        <div class="dropdown">
          <div class="text-right">
            Sort By
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Default
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Roomate</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>
            </div>

          </div>
          <ul class="list-group">
            <% @category.articles.each do |article| %>

                <li class="list-group-item list-group-item-light text-left">
                    <%= link_to article.title, article_path(article), class: "text-info" %>
                    <% if article.categories.any? %>
                      <div class="mt-1"> <%= render article.categories %> </div>
                    <% end %>
                    <div class="text-right">
                      <% if logged_in? && article.user == current_user %>
                        <%= link_to "Complete", article_path(article) %> -
                      <% end %>
                      <%= article.description %> -
                      <small> <i> Created <%= time_ago_in_words( article.created_at) %> ago by <%= article.user.username %> </i> </small>

                    </div>

                </li>

            <% end %>
          </ul>
          <br>

    </div>

  </div>



</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <small> <%= msg %> </small>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "ROOM 8", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item active">
          <%= link_to "Tasks", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Task", new_article_path, class: "nav-link" %>

        </li>
      <% end %>


      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>

      <% if logged_in? %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Edit Account", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Delete Account", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <div class="dropdown-divider"></div>
            <%= link_to "House Status", articles_path, class: "dropdown-item" %>
            <% if current_user.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to "All users", users_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>

      <% else %>

      <% end %>


    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBoi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<<h1>This is the About Page</h1>

<%= link_to "Articles Listing", articles_path %>

<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id = "home-container" >
    <div class="jumbotron text-center">
      <h1 class="display-2 " >Room 8</h1>
      <p class="lead text-white bg-dark">Welcome to Room 8. An easy way to keep roomates accountable for daily tasks, monthly payments, and other useful things
                      <br>It is free and easy to use!.</p>


      <%= link_to "Sign Up!", signup_path, class: "btn btn-secondary btn-lg btn-outline-light" %>
    </div>
  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "container-fluid text-center" id="page-content">

  <h1><strong>Edit Account </strong></h1>

  <%= render "form" %>



</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/users/index.html.erb
<div class = "container-fluid text-center" id="page-content">



  <div class="row">
    <div class="col-lg-5 shadow-lg p-3 mb-5 rounded" id="task-container-1">
      <h1>All Accounts</h1>
        <div class="dropdown">
          <div class="text-right">
            Sort By
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Default
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Roomate</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>
            </div>

          </div>
          <ul class="list-group">
            <% @users.each do |user| %>

                <li class="list-group-item list-group-item-light">
                    <%= link_to user.username, user_path(user) %>


                    <div class="text-right">
                      <%= gravatar_for user, size: 200 %>


                    </div>
                    <% if current_user.admin? %>
                      <%= link_to "Delete Account", user_path(user), class: "btn btn-dark btn-lg btn-outline-dark text-danger", method: :delete, data: {confirm: "Are you sure?"} %>

                    <% end %>

                </li>

            <% end %>
          </ul>
          <br>

    </div>

  </div>



</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/users/new.html.erb
<div class = "container-fluid text-center" id="page-content">

  <h1><strong>Sign up for Room8 </strong></h1>

  <%= render "form" %>



</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>

app/views/users/show.html.erb
<div class = "container-fluid text-center" id="page-content">

  <h1><strong> <%= @user.username %>'s profile</strong></h1>

  <%= gravatar_for @user, size: 200 %>

  <div class="mt-4">
    <% if logged_in? && @user == current_user %>
      <%= link_to "[ Edit Your Profile ]", edit_user_path(@user), class: "btn btn-outline-dark" %>
    <% end %>
  </div>


  <div class="row">
    <div class="col-lg-5 shadow-lg p-3 mb-5 rounded" id="task-container-1">
      <h1>Unfinished Tasks</h1>
        <div class="dropdown">
          <div class="text-right">
            Sort By
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Default
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Roomate</a>
                <a class="dropdown-item" href="#">Date</a>
                <a class="dropdown-item" href="#">Importance</a>
              </div>
            </div>

          </div>
          <ul class="list-group">
            <% @articles.each do |article| %>

                <li class="list-group-item list-group-item-light text-left">
                    <%= link_to article.title, article_path(article), class: "text-info" %>
                    <% if article.categories.any? %>
                      <div class="mt-1"> <%= render article.categories %> </div>
                    <% end %>
                    <div class="text-right">
                      <% if logged_in? && article.user == current_user %>
                        <%= link_to "Complete", article_path(article) %> -
                      <% end %>
                      <%= article.description %> -
                      <small> <i> Created <%= time_ago_in_words( article.created_at) %> ago by <%= article.user.username %> </i> </small>

                    </div>

                </li>

            <% end %>
          </ul>
          <br>

    </div>

  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Enzo </small>
      <br>
      <%= link_to "Articles Listing", articles_path %>
     |
      <%= link_to "About page", about_path %>
    </div>
</footer>